### ISSUE TITLE
AirPlay: Device Immediate Disconnect

### ISSUE THREAD

**Issue by stormsoftware** [ConnectSDK/Connect-SDK-iOS#145] opened 2015-04-21 12:54 UTC
Sometimes when connecting to my Apple TV (3rd gen), the device automatically gets disconnected as soon as the device connects.
I've been debugging and i've found that the device's targetURL is incorrect when checking for reachability in DeviceServiceReachability.m, Line 63 onwards:
- (void) checkReachability
{
    if (!_running)
        return;

    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:self.targetURL];
    [request setTimeoutInterval:10];
    [request setCachePolicy:NSURLRequestReloadIgnoringLocalCacheData];

I can see that when the problem doesn't occur the self.targetURL used the Apple TV's IP address and when the problem does occur it uses something entirely different, possibly the device's MAC address?

Has anybody else experienced this issue?

Thanks

**Comment by DevelopIdeas** [comment] 2015-04-21 19:33
After experiencing this issue myself and further debugging, this is a NSLog of the dictionary generated for my Apple TV in ServiceDescription.m (Line 55):
``` objectivec
//  ServiceDescription.m
// - (NSDictionary *) toJSONObject
dictionary: {
    UUID = "5C:F9:38:CE:8C";
    address = "fe80::1414:fe66:5afa:a8a2";
    commandURL = "http://fe80::1414:fe66:5afa:a8a2:7000/";
    friendlyName = "Apple TV";
    port = 7000;
    serviceId = AirPlay;
} 
```

**Comment by eunikolsky** [comment] 2015-04-22 00:43
@stormsoftware, @DevelopIdeas, thanks for the info. I did see this a few times before and was suspecting an IPv6 address. I'll try to reproduce this now.

SSDP discovery uses an explicit IPv4 for multicast UDP socket. And Zeroconf discovery uses Apple's framework, which apparently supports IPv6 as well. A hack would be to disable IPv6 support in Zeroconf discovery, and it should be fine since it's local network anyway.

**Comment by eunikolsky** [comment] 2015-04-22 01:36
When the device has resolved a zeroconf/mdns service, we get a callback with `addresses`, but the code only takes the first one: https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/dev/Discovery/Providers/ZeroConfDiscoveryProvider.m#L185

I'm thinking that if, for some reason, Apple TV doesn't get its IPv4 address (from DHCP), it's first resolved using its IPv6 address (`fe80::`, which is a link-local address). Then, an IPv4 address becomes available and we get a new callback with it. I'm not sure what happens next. I'd like to reproduce it somehow.

**Comment by DevelopIdeas** [comment] 2015-04-22 09:54
@eunikolsky I've been doing some testing again and the IPv6 address seems to be the one returned.
Is there any particular reason why IPv6 can't be supported as this would be the most future proof scenario?

**Comment by eunikolsky** [comment] 2015-04-22 16:20
@DevelopIdeas, agree, IPv6 should ideally be supported. The thing is I don't understand yet why the current setup doesn't work.

**Comment by eunikolsky** [comment] 2015-04-22 16:47
I've found the cause. Apple TV is disconnected by the `DeviceServiceReachability` class as pointed above. If you're connecting via IPv6, the target URL is `http://fe80::c48:e3ce:d170:6861:7000/`, which is incorrect:
```bash
$ curl 'http://fe80::c48:e3ce:d170:6861:7000/'
curl: (3) IPv6 numerical address used in URL without brackets
```
The IPv6 address should be in square brackets.

**Comment by DevelopIdeas** [comment] 2015-04-22 19:37
@eunikolsky I've come to the same conclusion as the address should be: http://[fe80::c48:e3ce:d170:6861]:7000/
I've addressed this by changing the stringWithFormat line of ZeroConfDiscoveryProvider.m to incorporate an NSString which I set accordingly further up dependant on whether the address is IPv4 or IPv6.

The problem I now face is that most routers (to my knowledge) don't have IPv6 enabled by default, my solution which seems to be working, but it needs testing.
In the event an IPv6 address if found, in the switch statement I now add a return:
``` objectivec
case AF_INET6: {
    NSLog(@"IPv6 Address, Skip It");
    return;
    /*struct sockaddr_in6 *ip6;
    char dest[INET6_ADDRSTRLEN];
    ip6 = (struct sockaddr_in6 *) [myData bytes];
    port = ntohs(ip6->sin6_port);
    address = [NSString stringWithFormat: @"%s",  inet_ntop(AF_INET6, &ip6->sin6_addr, dest, sizeof dest)];
    commandPathFormat = @"http://[%@]:%@/";*/
}
```
This ignores the rest of the switch block and the scanner then goes on to find the IPv4 address for my Apple TV and connects successfully.

**Comment by eunikolsky** [comment] 2015-04-22 20:05
@DevelopIdeas, yes, turns out it's not that simple. The actual working commands on OSX are:
```bash
curl -v 'http://[fe80::c48:e3ce:d170:6861%25en0]:7000/'
ping6 "fe80::c48:e3ce:d170:6861%en0"
```
Since `fe80::` is a link-local address, curl/ping/… need to know what interface to use, which is appended to the IP: `%en0`, which is encoded as `%25en0` (http://stackoverflow.com/questions/7358667/ipv6-max-os-x-10-6-ping-fails).

`NSURL`'s parser works properly with such url `[fe80::c48:e3ce:d170:6861%25en0]:7000`, and I'm able to connect to and control Apple TV.

The question is: how to get the interface for a resolved service (`NSNetService`) on iOS?

**Comment by DevelopIdeas** [comment] 2015-04-22 22:05
@eunikolsky I believe I have a solution, could you kindly tell me how to fork this project and submit a pull request?

**Comment by eunikolsky** [comment] 2015-04-22 22:43
@DevelopIdeas, what's your solution?  To fork, go to https://github.com/ConnectSDK/Connect-SDK-iOS and click the Fork button (https://help.github.com/articles/fork-a-repo/). Then you create and push a branch with your changes into your fork, and create a PR to our repo (https://help.github.com/articles/using-pull-requests).

There are two issues with using IPv6 now:

1. how to get the interface for a resolved service (`NSNetService`) on iOS?  We can assume it's `en0` if an iOS device has only one WiFi adapter.
2. currently, services are grouped into devices based on the IP address. so, if we resolve the same device with both IPs, it will be presented as two different devices currently.

We've decided to turn off IPv6 support in Zeroconf discovery for now, and implement proper support later (it should also be added to SSDP discovery).

**Comment by eunikolsky** [comment] 2015-04-22 23:13
**NB**: The Apple's docs suggest using hostnames instead of resolving IP addresses:
[Avoid Resolving DNS Names Before Connecting to a Host]
(https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/CommonPitfalls/CommonPitfalls.html#//apple_ref/doc/uid/TP40010220-CH4-SW20)

> As a rule, you should not resolve a service to an IP address and port number unless you are doing something very unusual.
> – [Connecting to a Bonjour Service by IP Address](https://developer.apple.com/library/mac/documentation/Networking/Conceptual/NSNetServiceProgGuide/Articles/ResolvingServices.html#//apple_ref/doc/uid/20001078-SW4)

That is, using a hostname can be the proper solution for implementing this.

**Comment by DevelopIdeas** [comment] 2015-04-23 07:02
@eunikolsky I've managed to find out how to get the Network Interface from the address but it still doesn't work, maybe your right and just avoid IPv6 using the 'return' solution I mentioned earlier

**Comment by eunikolsky** [comment] 2015-04-23 17:14
> I've managed to find out how to get the Network Interface from the address

@DevelopIdeas, how do you do that? iterating over all network interfaces?

**Comment by eunikolsky** [comment] 2015-04-23 18:01
Merged in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/27c30d2fd7efe369a87b85c615d59d2e4def5830 and https://github.com/ConnectSDK/Connect-SDK-iOS-Lite/commit/db1cee26134806aff3a3f39df71dae65b9dc24cc.

**Comment by DevelopIdeas** [comment] 2015-04-23 20:23
@eunikolsky Using this code you can get the network interface name for the IPv6 address:  
``` objectivec
#include <net/if.h>

char networkInterface[IF_NAMESIZE];
if_indextoname(ip6->sin6_scope_id, (char *)&networkInterface);
```

**Comment by eunikolsky** [comment] 2015-04-23 21:28
@DevelopIdeas, thanks for sharing! That does the trick indeed. Still, it'd be better if we could go forward with hostnames in the future.

**Closed** 2015-04-23 22:14 UTC
Labels: bug

**Comment by DevelopIdeas** [comment] 2015-04-23 22:15
@eunikolsky you're welcome, can you now connect to the Apple TV with theirs and the IPv6 address? as I can't seem to, I don't think my URL is formed properly as I can ping the address from the Mac command line but cannot make a HTTP request.

**Comment by eunikolsky** [comment] 2015-04-23 22:41
@DevelopIdeas, yes, I can. Reachability and commands work fine. The URL I construct is `http://[fe80::c48:e3ce:d170:6861%25en0]:7000/`. Here's the code:
```objc
case AF_INET6: {
    struct sockaddr_in6 *ip6;
    char dest[INET6_ADDRSTRLEN];
    ip6 = (struct sockaddr_in6 *) [data bytes];
    port = ntohs(ip6->sin6_port);
    char networkInterface[IF_NAMESIZE];
    if_indextoname(ip6->sin6_scope_id, (char *)&networkInterface);
    address = [NSString stringWithFormat: @"[%s%%25%s]",
                inet_ntop(AF_INET6, &ip6->sin6_addr, dest, sizeof dest),
                networkInterface];
    break;
}
```

**Comment by DevelopIdeas** [comment] 2015-04-23 23:00
@eunikolsky fantastic! slight typo on my end for the string formatting! I'm happy I could contribute!

**Comment by eunikolsky** [comment] 2015-04-23 23:35
@DevelopIdeas, agree, thanks for your help!
